language: python
dist: trusty
# We are going to need a full-VM.
sudo: enabled
# Vdist needs docker enabled to work.
services:
  - docker
python:
  - 2.7
  - 3.6
  - nightly
branches:
  only:
  - staging
  # Just for tests of travis_integration. Remove when integration is done.
  - travis_integration
notifications:
  recipients:
  - dante.signal31@gmail.com
  on_sucess: always
  on_failure: always
before_install:
  - sudo apt-get update -qq
  # To test we need docker.io but that comes already packaged in travis image
  # so we don't need to install it.
  - sudo apt-get install -qq libssl1.0.0 rpm
install:
  - pip install -r requirements.txt
env:
  - TEST_TAG="test_generate_deb"
  - TEST_TAG="centos6"
  - TEST_TAG="centos7"
script:
  - travis_wait 20 pytest -v -rs -k $TEST_TAG
#after_sucess:
#  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; ci-scripts/build_system_packages; fi



